# Generated by Django 5.2.6 on 2025-09-05 15:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Musteri",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ad_soyad_veya_unvan",
                    models.CharField(max_length=255, verbose_name="Ad Soyad / Ünvan"),
                ),
                ("telefon", models.CharField(blank=True, max_length=20, null=True)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("adres", models.TextField(blank=True, null=True)),
                (
                    "vergi_no",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Vergi Numarası",
                    ),
                ),
                (
                    "kayit_tarihi",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Kayıt Tarihi"
                    ),
                ),
            ],
            options={
                "verbose_name": "Müşteri",
                "verbose_name_plural": "Müşteriler",
            },
        ),
        migrations.CreateModel(
            name="Tedarikci",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "firma_adi",
                    models.CharField(max_length=255, verbose_name="Firma Adı"),
                ),
                (
                    "yetkili_kisi",
                    models.CharField(
                        blank=True,
                        max_length=150,
                        null=True,
                        verbose_name="Yetkili Kişi",
                    ),
                ),
                ("telefon", models.CharField(blank=True, max_length=20, null=True)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("adres", models.TextField(blank=True, null=True)),
                (
                    "kayit_tarihi",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Kayıt Tarihi"
                    ),
                ),
                (
                    "aktif_mi",
                    models.BooleanField(default=True, verbose_name="Aktif Mi?"),
                ),
            ],
            options={
                "verbose_name": "Tedarikçi",
                "verbose_name_plural": "Tedarikçiler",
            },
        ),
        migrations.CreateModel(
            name="Urun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "urun_kodu",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Ürün Kodu/Barkod"
                    ),
                ),
                ("urun_adi", models.CharField(max_length=255, verbose_name="Ürün Adı")),
                ("marka", models.CharField(blank=True, max_length=100, null=True)),
                ("model", models.CharField(blank=True, max_length=100, null=True)),
                ("ebat", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "mevsim",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Yaz", "Yaz"),
                            ("Kış", "Kış"),
                            ("4 Mevsim", "4 Mevsim"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "uretim_tarihi_dot",
                    models.CharField(
                        blank=True,
                        max_length=10,
                        null=True,
                        verbose_name="Üretim Tarihi (DOT)",
                    ),
                ),
                (
                    "yuk_endeksi",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Yük Endeksi"
                    ),
                ),
                (
                    "hiz_endeksi",
                    models.CharField(
                        blank=True, max_length=5, null=True, verbose_name="Hız Endeksi"
                    ),
                ),
                (
                    "mevcut_stok",
                    models.IntegerField(default=0, verbose_name="Mevcut Stok"),
                ),
                (
                    "kritik_stok_seviyesi",
                    models.IntegerField(default=5, verbose_name="Kritik Stok Seviyesi"),
                ),
                (
                    "aktif_mi",
                    models.BooleanField(default=True, verbose_name="Aktif Mi?"),
                ),
            ],
            options={
                "verbose_name": "Ürün",
                "verbose_name_plural": "Ürünler",
            },
        ),
        migrations.CreateModel(
            name="StokHareketi",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "islem_tipi",
                    models.CharField(
                        choices=[
                            ("Mal Alımı", "Mal Alımı"),
                            ("Satış", "Satış"),
                            ("İade (Giriş)", "İade (Giriş)"),
                            ("İade (Çıkış)", "İade (Çıkış)"),
                            ("Fire", "Fire"),
                        ],
                        max_length=20,
                        verbose_name="İşlem Tipi",
                    ),
                ),
                ("adet", models.IntegerField()),
                (
                    "birim_alis_fiyati",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Birim Alış Fiyatı (₺)",
                    ),
                ),
                (
                    "birim_satis_fiyati",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Birim Satış Fiyatı (₺)",
                    ),
                ),
                ("tarih", models.DateTimeField(auto_now_add=True)),
                (
                    "aciklama",
                    models.TextField(
                        blank=True, null=True, verbose_name="Açıklama (Fatura No vb.)"
                    ),
                ),
                (
                    "kullanici",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="İşlemi Yapan",
                    ),
                ),
                (
                    "musteri",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="envanter.musteri",
                    ),
                ),
                (
                    "tedarikci",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="envanter.tedarikci",
                    ),
                ),
                (
                    "urun",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="envanter.urun",
                        verbose_name="Ürün",
                    ),
                ),
            ],
            options={
                "verbose_name": "Stok Hareketi",
                "verbose_name_plural": "Stok Hareketleri",
            },
        ),
    ]
