# Generated by Django 5.2.6 on 2025-09-05 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("envanter", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Arac",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "plaka",
                    models.CharField(max_length=20, unique=True, verbose_name="Plaka"),
                ),
                ("marka", models.CharField(max_length=100, verbose_name="Marka")),
                ("model", models.CharField(max_length=100, verbose_name="Model")),
                ("yil", models.IntegerField(blank=True, null=True, verbose_name="Yıl")),
                (
                    "aktif_mi",
                    models.BooleanField(default=True, verbose_name="Filoda Aktif Mi?"),
                ),
            ],
            options={
                "verbose_name": "Araç",
                "verbose_name_plural": "Araçlar",
            },
        ),
    ]
