# Generated by Django 5.2.6 on 2025-09-05 18:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("envanter", "0002_arac"),
    ]

    operations = [
        migrations.AddField(
            model_name="stokhareketi",
            name="arac",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="envanter.arac",
                verbose_name="Araç",
            ),
        ),
        migrations.AlterField(
            model_name="stokhareketi",
            name="islem_tipi",
            field=models.CharField(
                choices=[
                    ("Mal Alımı", "Mal Alımı"),
                    ("Satış", "Satış"),
                    ("Servis Kullanımı", "Servis Kullanımı"),
                    ("İade (Giriş)", "İade (Giriş)"),
                    ("İade (Çıkış)", "İade (Çıkış)"),
                    ("Fire", "Fire"),
                ],
                max_length=20,
                verbose_name="İşlem Tipi",
            ),
        ),
    ]
