# Generated by Django 5.2.6 on 2025-09-05 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("envanter", "0003_stokhareketi_arac_alter_stokhareketi_islem_tipi"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stokhareketi",
            name="islem_tipi",
            field=models.CharField(
                choices=[
                    ("Mal Alımı", "Mal Alımı"),
                    ("Satış", "Satış"),
                    ("Servis Kullanımı", "Servis Kullanımı"),
                    ("İade (Giriş)", "İade (Giriş)"),
                    ("İade (Çıkış)", "İade (Çıkış)"),
                    ("Fire", "Fire"),
                ],
                max_length=30,
                verbose_name="İşlem Tipi",
            ),
        ),
    ]
