# Generated by Django 5.2.6 on 2025-09-05 22:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("envanter", "0004_alter_stokhareketi_islem_tipi"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stokhareketi",
            name="islem_tipi",
            field=models.CharField(
                choices=[
                    ("Mal Alımı", "Mal Alımı"),
                    ("Satış", "Satış"),
                    ("Servis Kullanımı", "Servis Kullanımı (Filo)"),
                    ("İade (Giriş)", "İade (Giriş)"),
                    ("İade (Çıkış)", "İade (Çıkış)"),
                    ("Fire", "Fire"),
                ],
                max_length=30,
                verbose_name="İşlem Tipi",
            ),
        ),
        migrations.CreateModel(
            name="Kiralama",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "baslangic_tarihi",
                    models.DateField(verbose_name="Kiralama Başlangıç Tarihi"),
                ),
                (
                    "bitis_tarihi",
                    models.DateField(
                        blank=True, null=True, verbose_name="Kiralama Bitiş Tarihi"
                    ),
                ),
                (
                    "gunluk_ucret",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Günlük Ücret (₺)"
                    ),
                ),
                (
                    "toplam_ucret",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Toplam Ücret (₺)",
                    ),
                ),
                (
                    "durum",
                    models.CharField(
                        choices=[
                            ("Rezerve", "Rezerve"),
                            ("Kirada", "Kirada"),
                            ("Tamamlandı", "Tamamlandı"),
                            ("İptal", "İptal"),
                        ],
                        default="Rezerve",
                        max_length=20,
                    ),
                ),
                ("kayit_tarihi", models.DateTimeField(auto_now_add=True)),
                (
                    "arac",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="envanter.arac",
                        verbose_name="Kiralanan Araç",
                    ),
                ),
                (
                    "musteri",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="envanter.musteri",
                        verbose_name="Kiralayan Müşteri",
                    ),
                ),
            ],
            options={
                "verbose_name": "Kiralama İşlemi",
                "verbose_name_plural": "Kiralama İşlemleri",
            },
        ),
    ]
